name: Publish

on:
  push:
    branches:
      - main

env:
  foo: 'bar'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with Astro
        run: yarn build
      - name: Deploy to B2 Storage
        uses: jakejarvis/backblaze-b2-action@master
        env:
          SOURCE_DIR: './dist'
          B2_BUCKET: ${{ secrets.B2_BUCKET }}
          B2_APPKEY_ID: ${{ secrets.B2_APPKEY_ID }}
          B2_APPKEY: ${{ secrets.B2_APPKEY }}
      # - name: Upload to CDN
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ny.storage.bunnycdn.com
      #     username: ${{ secrets.BUNNY_STORAGE_FTP_USERNAME }}
      #     password: ${{ secrets.BUNNY_STORAGE_FTP_PASSWORD }}
      #     local-dir: ./dist/

