name: Publish O. Brignoni

on:
  push:
    branches:
      - main

env:
  foo: 'bar'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with Astro
        run: yarn build
      - name: 📂 Upload to CDN
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          protocol: ftp
          port: 21
          server: ny.storage.bunnycdn.com
          username: ${{ secrets.BUNNY_STORAGE_FTP_USERNAME }}
          password: ${{ secrets.BUNNY_STORAGE_FTP_PASSWORD }}
          local-dir: ./dist/